START TRANSACTION;

-- Verify resume.EDUCATION
SELECT 1 FROM `EDUCATION` LIMIT 1;

-- Verify resume.EXPERIENCE
SELECT 1 FROM `EXPERIENCE` LIMIT 1;

-- Verify resume.SKILL
SELECT 1 FROM `SKILL` LIMIT 1;

-- Verify resume.SKILL_CATEGORY
SELECT 1 FROM `SKILL_CATEGORY` LIMIT 1;

-- Verify resume.EDUCATION_I18N
SELECT 1 FROM `EDUCATION_I18N` LIMIT 1;

-- Verify resume.EDUCATION_SKILL
SELECT 1 FROM `EDUCATION_SKILL` LIMIT 1;

-- Verify resume.EXPERIENCE_I18N
SELECT 1 FROM `EXPERIENCE_I18N` LIMIT 1;

-- Verify resume.EXPERIENCE_SKILL
SELECT 1 FROM `EXPERIENCE_SKILL` LIMIT 1;

-- Verify resume.SKILL_CATEGORY_I18N
SELECT 1 FROM `SKILL_CATEGORY_I18N` LIMIT 1;

-- Verify resume.SKILL_I18N
SELECT 1 FROM `SKILL_I18N` LIMIT 1;

-- Verify resume.SKILL_SKILL_CATEGORY
SELECT 1 FROM `SKILL_SKILL_CATEGORY` LIMIT 1;

ROLLBACK;