-- Verify alexicourieux-resume-db:001-init-data on mysql

START TRANSACTION;

SELECT 1 FROM `EXPERIENCE` WHERE ID = 'flo';
SELECT 1 FROM `EXPERIENCE_I18N` WHERE EXPERIENCE_ID = 'flo';
SELECT 1 FROM `EXPERIENCE_SKILL` WHERE EXPERIENCE_ID = 'flo' AND SKILL_ID = 'ci_cd';
SELECT 1 FROM `EDUCATION` WHERE ID = 1;
SELECT 1 FROM `EDUCATION_I18N` WHERE EDUCATION_ID = 1;
SELECT 1 FROM `SKILL` WHERE ID = 'agile';
SELECT 1 FROM `SKILL_I18N` WHERE SKILL_ID = 'agile';
SELECT 1 FROM `SKILL_CATEGORY` WHERE ID = 'backend';
SELECT 1 FROM `SKILL_CATEGORY_I18N` WHERE SKILL_CATEGORY_ID = 'backend';
SELECT 1 FROM `SKILL_SKILL_CATEGORY` WHERE SKILL_ID = 'angular' AND SKILL_CATEGORY_ID = 'frontend';

ROLLBACK;
