services:
  db:
    build:
      context: docker/db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_root_password
      - mysql_password
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_password:
    file: ./secrets/mysql_password.txt

volumes:
  db_data: