-- Drop tables in reverse order of creation to handle foreign key dependencies
START TRANSACTION;

-- Drop resume.SKILL_SKILL_CATEGORY
DROP TABLE IF EXISTS `SKILL_SKILL_CATEGORY`;

-- Drop resume.SKILL_I18N
DROP TABLE IF EXISTS `SKILL_I18N`;

-- Drop resume.SKILL_CATEGORY_I18N
DROP TABLE IF EXISTS `SKILL_CATEGORY_I18N`;

-- Drop resume.EXPERIENCE_SKILL
DROP TABLE IF EXISTS `EXPERIENCE_SKILL`;

-- Drop resume.EXPERIENCE_I18N
DROP TABLE IF EXISTS `EXPERIENCE_I18N`;

-- Drop resume.EDUCATION_SKILL
DROP TABLE IF EXISTS `EDUCATION_SKILL`;

-- Drop resume.EDUCATION_I18N
DROP TABLE IF EXISTS `EDUCATION_I18N`;

-- Drop resume.SKILL_CATEGORY
DROP TABLE IF EXISTS `SKILL_CATEGORY`;

-- Drop resume.SKILL
DROP TABLE IF EXISTS `SKILL`;

-- Drop resume.EXPERIENCE
DROP TABLE IF EXISTS `EXPERIENCE`;

-- Drop resume.EDUCATION
DROP TABLE IF EXISTS `EDUCATION`;

COMMIT;