-- Revert alexicourieux-resume-db:002-experience-logo-uri from mysql

START TRANSACTION;

-- Drop columns from EXPERIENCE_I18N
ALTER TABLE `EXPERIENCE_I18N` DROP COLUMN `IMAGE_URI`;
ALTER TABLE `EXPERIENCE_I18N` DROP COLUMN `IMAGE_URI_DARK`;
ALTER TABLE `EXPERIENCE_I18N` DROP COLUMN `IMAGE_ALT`;

COMMIT;
