-- Deploy alexicourieux-resume-db:000-init to mysql

START TRANSACTION;

-- resume.EDUCATION definition

CREATE TABLE `EDUCATION` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `START_DATE` datetime DEFAULT NULL,
  `END_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;


-- resume.EXPERIENCE definition

CREATE TABLE `EXPERIENCE` (
  `ID` varchar(100) NOT NULL,
  `START_DATE` date DEFAULT NULL,
  `END_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- resume.SKILL definition

CREATE TABLE `SKILL` (
  `ID` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- resume.SKILL_CATEGORY definition

CREATE TABLE `SKILL_CATEGORY` (
  `ID` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- resume.EDUCATION_I18N definition

CREATE TABLE `EDUCATION_I18N` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `EDUCATION_ID` int NOT NULL,
  `SCHOOL` varchar(255) NOT NULL,
  `DEGREE` varchar(255) NOT NULL,
  `LANGUAGE` varchar(2) NOT NULL DEFAULT 'EN',
  `LOCATION` varchar(100) NOT NULL,
  `IMAGE_URI` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `EDUCATION_ID` (`EDUCATION_ID`),
  CONSTRAINT `EDUCATION_I18N_ibfk_1` FOREIGN KEY (`EDUCATION_ID`) REFERENCES `EDUCATION` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;


-- resume.EDUCATION_SKILL definition

CREATE TABLE `EDUCATION_SKILL` (
  `ID` int NOT NULL,
  `EDUCATION_ID` int DEFAULT NULL,
  `SKILL_ID` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `EDUCATION_ID` (`EDUCATION_ID`),
  KEY `SKILL_ID` (`SKILL_ID`),
  CONSTRAINT `EDUCATION_SKILL_ibfk_1` FOREIGN KEY (`EDUCATION_ID`) REFERENCES `EDUCATION` (`ID`),
  CONSTRAINT `EDUCATION_SKILL_ibfk_2` FOREIGN KEY (`SKILL_ID`) REFERENCES `SKILL` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- resume.EXPERIENCE_I18N definition

CREATE TABLE `EXPERIENCE_I18N` (
  `EXPERIENCE_ID` varchar(100) NOT NULL,
  `POSITION` varchar(100) NOT NULL,
  `SHORT_DESCRIPTION` tinytext,
  `DESCRIPTION` text,
  `COMPANY_NAME` varchar(100) NOT NULL,
  `LANGUAGE` varchar(2) NOT NULL DEFAULT 'EN',
  `ID` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `EXPERIENCE_I18N_UNIQUE` (`EXPERIENCE_ID`,`LANGUAGE`),
  CONSTRAINT `EXPERIENCE_I18N_EXPERIENCE_fk` FOREIGN KEY (`EXPERIENCE_ID`) REFERENCES `EXPERIENCE` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1;


-- resume.EXPERIENCE_SKILL definition

CREATE TABLE `EXPERIENCE_SKILL` (
  `EXPERIENCE_ID` varchar(100) NOT NULL,
  `SKILL_ID` varchar(100) NOT NULL,
  `ID` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `COMPANY_SKILL_UNIQUE` (`EXPERIENCE_ID`,`SKILL_ID`),
  KEY `EXPERIENCE_SKILL_SKILL_fk` (`SKILL_ID`),
  CONSTRAINT `EXPERIENCE_SKILL_EXPERIENCE_fk` FOREIGN KEY (`EXPERIENCE_ID`) REFERENCES `EXPERIENCE` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `EXPERIENCE_SKILL_SKILL_fk` FOREIGN KEY (`SKILL_ID`) REFERENCES `SKILL` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=97 DEFAULT CHARSET=latin1;


-- resume.SKILL_CATEGORY_I18N definition

CREATE TABLE `SKILL_CATEGORY_I18N` (
  `SKILL_CATEGORY_ID` varchar(100) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `LANGUAGE` varchar(2) NOT NULL DEFAULT 'EN',
  `ID` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SKILL_CATEGORY_I18N_UNIQUE` (`SKILL_CATEGORY_ID`,`LANGUAGE`),
  CONSTRAINT `SKILL_CATEGORY_I18N_CATEGORY_FK` FOREIGN KEY (`SKILL_CATEGORY_ID`) REFERENCES `SKILL_CATEGORY` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=latin1;


-- resume.SKILL_I18N definition

CREATE TABLE `SKILL_I18N` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `SKILL_ID` varchar(100) NOT NULL,
  `LANGUAGE` varchar(2) NOT NULL DEFAULT 'EN',
  `NAME` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SKILL_I18N_UNIQUE` (`SKILL_ID`,`LANGUAGE`),
  CONSTRAINT `SKILL_I18N_SKILL_FK` FOREIGN KEY (`SKILL_ID`) REFERENCES `SKILL` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=127 DEFAULT CHARSET=latin1;


-- resume.SKILL_SKILL_CATEGORY definition

CREATE TABLE `SKILL_SKILL_CATEGORY` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `SKILL_ID` varchar(100) DEFAULT NULL,
  `SKILL_CATEGORY_ID` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SKILL_NAME` (`SKILL_ID`,`SKILL_CATEGORY_ID`),
  KEY `SKILL_SKILL_CATEGORY_CATEGORY_fk` (`SKILL_CATEGORY_ID`),
  CONSTRAINT `SKILL_SKILL_CATEGORY_CATEGORY_fk` FOREIGN KEY (`SKILL_CATEGORY_ID`) REFERENCES `SKILL_CATEGORY` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `SKILL_SKILL_CATEGORY_SKILL_fk` FOREIGN KEY (`SKILL_ID`) REFERENCES `SKILL` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=190 DEFAULT CHARSET=latin1;

COMMIT;