name: build-and-deploy

on:
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: 'Deployment Environment'
        required: true
        default: 'production'
        type: choice
        options:
          - 'production'
      clean_ftp:
        description: 'Clean FTP'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.deploy_environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./app/
          server-dir: /
          state-name: api_content
          dangerous-clean-slate: ${{ github.event.inputs.clean_ftp }}
